apiVersion: v1
name: harbor
version: 1.2.0-dev
appVersion: dev
description: Harbor 是一个开源的容器镜像管理仓库。
keywords:
- docker
- registry
- harbor
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/harbor/master/docs/img/harbor_logo.png
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
maintainers:
- name: Wenkai Yin
  email: yinw@vmware.com
- name: Weiwei He
  email: hweiwei@vmware.com
engine: gotpl
