appVersion: 9.5.10
name: gitlab
description: GitLab 社区版是一个基于Web的 DevOps的生命周期工具。
home: https://www.kubeoperator.io
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
version: 1.0.0
