appVersion: 9.5.10
description: Fit2cloud GitLab
home: https://www.kubeoperator.io
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
name: fit2cloud-gitlab
version: 1.0.0
