apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "jenkins.fullname" . }}-{{ .Chart.Version }}"
  #namespace: jenkins
data:
    .dockerconfigjson: $secret
type: kubernetes.io/dockerconfigjson
