apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: kubeapps-registry-fit2cloud-com-key
metadata:
  name: {{ template "kubeapps.apprepository.fullname" . }}
  labels:
    app: {{ template "kubeapps.apprepository.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
